# Generated by Django 3.2.7 on 2021-09-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False)),
                ('write', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Access',
                'db_table': 'Access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=200)),
                ('list_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lists',
                'db_table': 'Lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reset_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('repeat', models.IntegerField(blank=True, null=True)),
                ('task_description', models.CharField(blank=True, max_length=10485760, null=True)),
                ('task_completed_date', models.DateTimeField(blank=True, null=True)),
                ('recur_ind', models.IntegerField(blank=True, null=True)),
                ('recur_days', models.IntegerField(blank=True, null=True)),
                ('parent_task_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'db_table': 'Tasks',
                'managed': False,
            },
        ),
    ]
